parameters:
#    sopinet_notifier.example.class: Sopinet\NotifierBundle\Example

#services:
#    sopinet_notifier.example:
#        class: %sopinet_notifier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
