parameters:
#    sopinet_open_map.example.class: Sopinet\OpenMapBundle\Example

services:
#    sopinet_open_map.example:
#        class: %sopinet_open_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
