# Sonata Admin Dashboard
sonata_admin:
    security:
        handler: custom.sonata.security.handler.role

    title:       Trazeo
    title_logo:  favicon.ico

    templates:
        # other configuration options
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

    dashboard:
        blocks:
           - { position: left,  type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>¡Bienvenido!</h3></div><div class='panel-body'>Podras gestionar tu cuenta de Trazeo Premium desde este panel. Recuerda que cualquier duda puedes acudir a nuestro servicio de soporte a traves de <a href='mailto:soportepremium@trazeo.es'>soportepremium@trazeo.es</a>.</div></div>"} }
           - { position: right,  type: sonata.block.mypagebundle.stats }
           - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [manageGroups] } }

        groups:
            manageGroups:
                label: Gestión de Rutas
                icon:            '<i class="fa fa-th"></i>'
                items:
                  - trazeo_base.admin.e_group
            manageRoutes:
                label: Gestión de Usuarios
                icon:            '<i class="fa fa-user"></i>'
                items:
                  - trazeo_base.admin.e_child
                  - trazeo_base.admin.user_extend

# Sonata
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.mypagebundle.stats:
        sonata.admin.block.search_result:
            contexts: [admin]