imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "../../vendor/sopinet/userbundle/Sopinet/UserBundle/Resources/config/config.yml" }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

parameters:
    #sopinet_user_facebook_id: "202407359917838"
    #sopinet_user_facebook_secret: "5963af0550e8be4b14fc40413f63f72b"
    sopinet_user_google_id: "117653870600-b4p1coann87l067i57rdcah8jpksb6ba.apps.googleusercontent.com"
    sopinet_user_google_secret: "5g0PxCoOCnDQe7dADh-zeI7V"
    #sopinet_user_sucess: "trazeo.login_success_handler"

framework:
    #esi:            ~
    translator:      { fallback: es }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true    

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"
        base_url: %base_url%
        exchange_code: %exchange_code%
    form:
        resources:
            - 'SopinetTemplateSbadmin2Bundle:Form:bootstrap.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FOSCommentBundle, SopinetTemplateSbadmin2Bundle, TrazeoFrontBundle, SopinetTemplateLandingBundle,SopinetTemplateAmoebaBundle, JMSTranslationBundle, FOSUserBundle, SopinetFlashMessagesBundle, SopinetTimelineBundle, SopinetSuggestionBundle, SopinetUploadMagicBundle, TrazeoMyPageBundle, SonataAdminBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            point: point
            enum: string
        types:
            point: Sopinet\Bundle\SimplePointBundle\DBAL\Types\SimplePointType
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        dql:
            numeric_functions:
                distance: Sopinet\Bundle\SimplePointBundle\ORM\MySQL\Distance
                point_str: Sopinet\Bundle\SimplePointBundle\ORM\MySQL\PointStr
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        
#KNP_menu
knp_menu:
    twig:
        template: SopinetTemplateSbadmin2Bundle:Elements:knp_menu.html.twig

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    encryption: tls
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type:                 file
        path:                 "%kernel.cache_dir%/swiftmailer/spool"

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
          group_class: Trazeo\BaseBundle\Entity\Group
    registration:
        form:
            type: trazeo_user_registration
            name: trazeo_user_registration_form
            validation_groups:  [Registration, Default]

# Sonata User
sonata_user:
    admin:
        user:
            class:  Trazeo\BaseBundle\Admin\UserAdmin

# Sonata Admin Dashboard
sonata_admin:
    title:      Trazeo - Dashboard
    templates:
        ## default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        ## default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [admin] } }

sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
        
services:
    #apikey_authenticator:
     #   class:     Trazeo\BaseBundle\Security\ApiKeyAuthenticator
      #  arguments: ["@webservice_user_provider"]
    trazeo.user_manager:
        class: Application\Sonata\UserBundle\Entity\User  
    
    encoderback:
        class: Trazeo\BaseBundle\Service\EncoderBack
    
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
              - name: twig.extension
    trazeo.updatedlistener:
        class: Trazeo\BaseBundle\Listener\UpdatedListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }
    sopinet_flashMessages:
        class:        Sopinet\FlashMessagesBundle\Service\FlashNotifier
        arguments:
            entityManager: @doctrine.orm.entity_manager
            container: @service_container
    sopinet.uploadlistener:
        class: Sopinet\Bundle\UploadMagicBundle\Listener\UploadListener
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_dirs: [cache, data, logs]
            extractors: [sonata_admin]

#FOSRest
fos_rest:
    routing_loader:
        default_format: json

#FOSComment
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Sopinet\TimelineBundle\Entity\Comment
            thread: Sopinet\TimelineBundle\Entity\Thread
            vote: Sopinet\TimelineBundle\Entity\Vote

            
#Lunetics LocaleBundle
lunetics_locale:
    strict_mode: true
    allowed_locales:
       - es    
       - en
    guessing_order:
       - query
       - router           
       - session
       - cookie
       - browser
    cookie:
       set_on_change: true
       
sopinet_gamification:
    class: 'TrazeoBaseBundle:UserExtend'      
    api: 'CiviClub'
sopinet_suggestion: ~

sopinet_autologin:
    domain: http://localhost/trazeo-web/web/app_dev.php/

hip_mandrill:
    api_key: sG8TY_s5xMA6wOvc9gLMmg
    disable_delivery: false # useful for dev/test environment. Default value is 'false'
    default:
        sender: hola@trazeo.es
        sender_name: Trazeo
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone

security:
    firewalls:
        main:
            pattern:    ^/
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                login_path: /login
                use_forward: false
                check_path: /login_check
                success_handler: %sopinet_user_sucess%
                csrf_provider: form.csrf_provider
                failure_path: null
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /login
                default_target_path: /panel
                failure_path: /login
                oauth_user_provider:
                    service: sopinet_user_provider
            switch_user: true

nelmio_api_doc: ~

jms_serializer:
  metadata:
    auto_detection: true
    directories:
      SopinetChatBundle:
        namespace_prefix: "Sopinet\\Bundle\\ChatBundle"
        path: "@SopinetChatBundle/Resources/config/serializer"

rms_push_notifications:
    android:
        gcm:
            api_key: %gcm_api_key%