imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "../../vendor/sopinet/userbundle/Sopinet/UserBundle/Resources/config/config.yml" }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }    

framework:
    #esi:            ~
    translator:      { fallback: es }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true    

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"
    form:
        resources:
            - 'SopinetTemplateSbadmin2Bundle:Form:bootstrap.html.twig'  

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FOSCommentBundle, SopinetTemplateSbadmin2Bundle, TrazeoFrontBundle, SopinetTemplateLandingBundle,SopinetTemplateAmoebaBundle, JMSTranslationBundle, FOSUserBundle, SopinetFlashMessagesBundle, SopinetTimelineBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            point: point
            enum: string
        types:
            point: Sopinet\Bundle\SimplePointBundle\DBAL\Types\SimplePointType
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        dql:
            numeric_functions:
                distance: Sopinet\Bundle\SimplePointBundle\ORM\MySQL\Distance
                point_str: Sopinet\Bundle\SimplePointBundle\ORM\MySQL\PointStr
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        
#KNP_menu
knp_menu:
    twig:
        template: SopinetTemplateSbadmin2Bundle:Elements:knp_menu.html.twig

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    encryption: tls
    host:      smtp.trazeo.es
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle Configuration

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
          group_class: Trazeo\BaseBundle\Entity\Group
          
# Sonata Admin Dashboard
sonata_admin:
    title:      Trazeo - Dashboard
    templates:
        ## default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        ## default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        
    dashboard:
        blocks:
            - { position: left, type: sonata.block.service.text, settings: { content: "Elementos"} }
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [Trazeo] } } 


# Sonata 

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        sonata.block.service.tableinput:
        
services:
    #apikey_authenticator:
     #   class:     Trazeo\BaseBundle\Security\ApiKeyAuthenticator
      #  arguments: ["@webservice_user_provider"]

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
              - name: twig.extension
    trazeo.updatedlistener:
        class: Trazeo\BaseBundle\Listener\UpdatedListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }     
    sopinet_flashMessages:
        class:        Sopinet\FlashMessagesBundle\Service\FlashNotifier
        arguments:
            entityManager: @doctrine.orm.entity_manager
            container: @service_container
              
jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_dirs: [cache, data, logs]
            extractors: [sonata_admin]
            
#hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
 #   firewall_name: secured_area

#FOSRest
fos_rest:
    routing_loader:
        default_format: json

#FOSComment
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Sopinet\TimelineBundle\Entity\Comment
            thread: Sopinet\TimelineBundle\Entity\Thread
            vote: Sopinet\TimelineBundle\Entity\Vote
            

   