parameters:
<<<<<<< HEAD
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     trazeo2
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       no-reply@trazeo.es
    mailer_password:   trazeando2013
    mailer_port:       false

    locale:            es
    secret:            ThisTokenIsNotSoSecretChangeIt
    base_url: "http://beta.trazeo.es"

    sopinet_user_facebook_id: "205484272995443"
    sopinet_user_facebook_secret: "32285c7ced8a532db4ae0e9e0dfd68e9"
    sopinet_user_google_id: "YOURID-GOOGLE"
    sopinet_user_google_secret: "YOURSECRET-GOOGLE"
    sopinet_user_sucess: "trazeo.login_success_handler"

    sopinet_user_civiclub_security: "yPonDzEz6L1W"
    sopinet_user_civiclub_emitter_id: "76"
    sopinet_user_civiclub_emitter_center_id: "127"
    sopinet_user_civiclub_service_id: "221"

    exchange_code: "12710416980574536028886"
