hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    pattern: /login/check-google
    
sopinet_user_notifications:
    resource: "@SopinetUserNotificationsBundle/Resources/config/routing.yml"
    prefix:   /
    
sopinet_flash_messages:
    resource: "@SopinetFlashMessagesBundle/Resources/config/routing.yml"
    prefix:   /

sopinet_user_preferences:
    resource: "@SopinetUserPreferencesBundle/Resources/config/routing.yml"
    prefix:   /

sopinet_open_map:
    resource: "@SopinetOpenMapBundle/Resources/config/routing.yml"
    prefix:   /

sopinet_timeline:
    resource: "@SopinetTimelineBundle/Resources/config/routing.yml"
    prefix:   /

sopinet_template_landing:
    resource: "@SopinetTemplateLandingBundle/Resources/config/routing.yml"
    prefix:   /

sopinet_template_amoeba:
    resource: "@SopinetTemplateAmoebaBundle/Resources/config/routing.yml"
    prefix:   /

trazeo_front:
    resource: "@TrazeoFrontBundle/Resources/config/routing.yml"
    prefix:   /

trazeo_base:
    resource: "@TrazeoBaseBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
 
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
# END Sonata Admin

sopinet_template_sbadmin2:
    resource: "@SopinetTemplateSbadmin2Bundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
panel:
    pattern: /panel
    
JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
    
EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode