security:
    encoders:    
        FOS\UserBundle\Model\UserInterface:
            id: encoderback
        #Trazeo\BaseBundle\Security\User\WebserviceUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        #webservice:
         #   id: webservice_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username

    
           

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }       
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/panel, role: ROLE_USER }