security:
    access_decision_manager:
        strategy: unanimous

    acl:
        connection: default

    encoders:    
        FOS\UserBundle\Model\UserInterface:
            id: encoderback
        #Trazeo\BaseBundle\Security\User\WebserviceUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_CATALOG]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_TRANS:       ROLE_TRANS
        ROLE_CATALOG:     ROLE_CATALOG

    providers:
        #webservice:
         #   id: webservice_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username_email
           
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }       
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_SONATA_ADMIN, ROLE_ADMIN] }
        # ->Catalog access
        - { path: ^/catalogitem, role: [ROLE_CATALOG] }
        # -> end        
        - { path: ^/panel, role: ROLE_USER }
        - { path: ^/_trans, role: [ROLE_TRANS, ROLE_ADMIN] }