parameters:
#    sopinet_template_test.example.class: Sopinet\Template\TestBundle\Example

services:
#    sopinet_template_test.example:
#        class: %sopinet_template_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
