parameters:
#    trazeo_base.example.class: Trazeo\BaseBundle\Example

services:
#    trazeo_base.example:
#        class: %trazeo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
