parameters:
#    trazeo_base.example.class: Trazeo\BaseBundle\Example

services:
#    trazeo_base.example:
#        class: %trazeo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    Trazeo.BaseBundle.Admin.ChildrenAdmin:
        class: Trazeo\BaseBundle\Admin\ChildrenAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: TuMuseo, label: ChildrenAdmin.php }
        arguments: [null, Trazeo\BaseBundle\Entity\Children, SonataAdminBundle:CRUD]
    Trazeo.BaseBundle.Admin.GroupsAdmin:
        class: Trazeo\BaseBundle\Admin\GroupsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: TuMuseo, label: GroupsAdmin.php }
        arguments: [null, Trazeo\BaseBundle\Entity\Groups, SonataAdminBundle:CRUD]
    Trazeo.BaseBundle.Admin.RouteAdmin:
        class: Trazeo\BaseBundle\Admin\RouteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: TuMuseo, label: RouteAdmin.php }
        arguments: [null, Trazeo\BaseBundle\Entity\Route, SonataAdminBundle:CRUD]
    Trazeo.BaseBundle.Admin.UserExtendAdmin:
        class: Trazeo\BaseBundle\Admin\UserExtendAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: TuMuseo, label: UserExtendAdmin.php }
        arguments: [null, Trazeo\BaseBundle\Entity\UserExtend, SonataAdminBundle:CRUD]
