panel:
    resource: "@TrazeoFrontBundle/Controller/PanelController.php"
    type:     annotation

public:
    resource: "@TrazeoFrontBundle/Controller/PublicController.php"
    type:     annotation
    
profile:
    resource: "@TrazeoFrontBundle/Controller/ProfileController.php"
    type:     annotation

prev_registro:
    resource: "@TrazeoFrontBundle/Controller/PrevRegistroController.php"
    type:     annotation
    
children:
    resource: "@TrazeoFrontBundle/Controller/PanelChildrenController.php"
    type:     annotation
    
groups:
    resource: "@TrazeoFrontBundle/Controller/PanelGroupsController.php"
    type:     annotation  

point:
    resource: "@TrazeoFrontBundle/Controller/PanelPointController.php"
    type:     annotation
    
routes:
    resource: "@TrazeoFrontBundle/Controller/PanelRoutesController.php"
    type:     annotation
    
rides:
    type:     annotation  
    resource: "@TrazeoFrontBundle/Controller/PanelRidesController.php"
    
userextend:
    resource: "@TrazeoFrontBundle/Controller/PanelUserController.php"
    type:     annotation
    
settings:
    resource: "@TrazeoFrontBundle/Controller/PanelSettingsController.php"
    type:     annotation
    
api:
    resource: "@TrazeoFrontBundle/Controller/ApiCheckController.php"
    type:     annotation