parameters:
#    trazeo_front.example.class: Trazeo\FrontBundle\Example

services:
#    trazeo_front.example:
#        class: %trazeo_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
