parameters:
#    trazeo_front.example.class: Trazeo\FrontBundle\Example

services:
    form.service:
        class: Trazeo\BaseBundle\Form
        calls:
            - [ setContainer, [ "@service_container" ] ]
