parameters:
#    sopinet_gamification.example.class: Sopinet\Bundle\GamificationBundle\Example

services:
#    sopinet_gamification.example:
#        class: %sopinet_gamification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
